export const GET_JOBS = "GET_JOBS";
export const GET_JOBS_FULFILLED = "GET_JOBS_FULFILLED";
export const GET_JOBS_PENDING = "GET_JOBS_PENDING";
export const GET_JOBS_REFUSED = "GET_JOBS_REFUSED";

export const ADD_NEW_JOB = "ADD_NEW_JOB";
export const ADD_NEW_JOB_FULFILLED = "ADD_NEW_JOB_FULFILLED";
export const ADD_NEW_JOB_PENDING = "ADD_NEW_JOB_PENDING";
export const ADD_NEW_JOB_REFUSED = "ADD_NEW_JOB_REFUSED";